env:
  - GHCVER=7.6.3
  - GHCVER=7.8.2
before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update -qq
  - sudo apt-get --no-install-recommends install libgtk2.0-dev libgtk-3-dev alex happy
  - sudo apt-get install cabal-install-1.18 ghc-$GHCVER
  - export CABAL=cabal-1.18
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:$PATH
  - $CABAL update
  - |
    if [ $GHCVER = "head" ] || [ $GHCVER = "7.8.2" ]; then
      $CABAL install happy alex
    fi
  - $CABAL install Cabal
install:
  - $CABAL install cabal-meta cabal-src
script:
  - ./install-both.sh
notifications:
  irc:
    channels: "irc.freenode.net#gtk2hs"
    skip_join: true
  email: true
